import { WidgetType } from './pageBuilderTypes';

export interface DesignCapabilities {
  colors: boolean;
  buttons: boolean;
  borders: boolean;
  shadows: boolean;
  background: boolean;
  spacing: boolean;
  typography: boolean;
  effects: boolean;
  layout: boolean;
}

const widgetCapabilities: Record<WidgetType, DesignCapabilities> = {
  header: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  hero: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: true,
    layout: true,
  },
  features: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  cta: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  content: {
    colors: true,
    buttons: false,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  testimonials: {
    colors: true,
    buttons: false,
    borders: true,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  contact: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  footer: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  pricing: {
    colors: true,
    buttons: true,
    borders: true,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  stats: {
    colors: true,
    buttons: false,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  team: {
    colors: true,
    buttons: false,
    borders: false,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  faq: {
    colors: true,
    buttons: false,
    borders: true,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  logocloud: {
    colors: true,
    buttons: false,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  videohero: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: true,
    layout: true,
  },
  gallery: {
    colors: true,
    buttons: false,
    borders: true,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  timeline: {
    colors: true,
    buttons: false,
    borders: true,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  newsletter: {
    colors: true,
    buttons: true,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
  process: {
    colors: true,
    buttons: false,
    borders: false,
    shadows: false,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  },
};

export function getWidgetCapabilities(widgetType: WidgetType | string): DesignCapabilities {
  if (widgetType in widgetCapabilities) {
    return widgetCapabilities[widgetType as WidgetType];
  }

  return {
    colors: true,
    buttons: true,
    borders: true,
    shadows: true,
    background: true,
    spacing: true,
    typography: true,
    effects: false,
    layout: true,
  };
}
