import { WidgetDefinition } from './pageBuilderTypes';

export const widgetLibrary: WidgetDefinition[] = [
  {
    type: 'header',
    label: 'Header',
    description: 'Navigation bar with logo and menu items',
    icon: 'layout',
    category: 'navigation',
    unique: true,
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'centered', label: 'Centered' },
      { id: 'transparent', label: 'Transparent' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      logo: '',
      logoText: 'Brand',
      navItems: [
        { label: 'Home', link: '#' },
        { label: 'About', link: '#' },
        { label: 'Services', link: '#' },
        { label: 'Contact', link: '#' },
      ],
      ctaText: 'Get Started',
      ctaLink: '#',
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#ffffff',
      },
      spacing: {
        paddingTop: '0px',
        paddingBottom: '0px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'hero',
    label: 'Hero Section',
    description: 'Large banner with headline and call-to-action',
    icon: 'monitor',
    variants: [
      { id: 'default', label: 'Classic' },
      { id: 'centered', label: 'Centered' },
      { id: 'split', label: 'Split Screen' },
      { id: 'minimal', label: 'Minimal' },
      { id: 'full-background', label: 'Full Background' },
    ],
    defaultContent: {
      headline: 'Your Amazing Headline',
      subheadline: 'A compelling subheadline that explains your value proposition',
      ctaText: 'Get Started',
      ctaLink: '#',
      image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#ffffff',
      },
      spacing: {
        paddingTop: '96px',
        paddingBottom: '96px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'features',
    label: 'Features Section',
    description: 'Showcase your product features in a grid',
    icon: 'grid',
    variants: [
      { id: 'grid-2', label: '2 Columns' },
      { id: 'grid-3', label: '3 Columns' },
      { id: 'grid-4', label: '4 Columns' },
      { id: 'alternating', label: 'Alternating' },
    ],
    defaultContent: {
      title: 'Amazing Features',
      subtitle: 'Everything you need to succeed',
      features: [
        {
          icon: 'zap',
          title: 'Lightning Fast',
          description: 'Optimized for performance and speed',
        },
        {
          icon: 'shield',
          title: 'Secure',
          description: 'Built with security best practices',
        },
        {
          icon: 'heart',
          title: 'User Friendly',
          description: 'Intuitive interface anyone can use',
        },
      ],
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#f9fafb',
      },
      spacing: {
        paddingTop: '80px',
        paddingBottom: '80px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'cta',
    label: 'Call to Action',
    description: 'Encourage users to take action',
    icon: 'mouse-pointer',
    variants: [
      { id: 'banner', label: 'Banner' },
      { id: 'centered', label: 'Centered Box' },
      { id: 'split', label: 'Split with Image' },
    ],
    defaultContent: {
      headline: 'Ready to Get Started?',
      description: 'Join thousands of satisfied customers today',
      primaryCta: 'Start Free Trial',
      primaryLink: '#',
      secondaryCta: 'Learn More',
      secondaryLink: '#',
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#000000',
      },
      spacing: {
        paddingTop: '64px',
        paddingBottom: '64px',
        marginTop: '0px',
        marginBottom: '0px',
      },
      typography: {
        fontFamily: 'inherit',
        fontSize: '1rem',
        lineHeight: '1.5',
      },
    },
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    description: 'Display customer reviews and testimonials',
    icon: 'message-square',
    variants: [
      { id: 'grid', label: 'Grid' },
      { id: 'carousel', label: 'Carousel' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'What Our Customers Say',
      subtitle: 'Trusted by thousands of happy customers',
      testimonials: [
        {
          quote: 'This product has completely transformed the way we work. Highly recommended!',
          name: 'Sarah Johnson',
          title: 'CEO, Tech Corp',
          avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
          rating: 5,
        },
        {
          quote: 'Amazing support team and great features. Worth every penny.',
          name: 'Michael Chen',
          title: 'Product Manager',
          avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
          rating: 5,
        },
        {
          quote: 'Simple, powerful, and elegant. Exactly what we needed.',
          name: 'Emily Rodriguez',
          title: 'Designer',
          avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400',
          rating: 5,
        },
      ],
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#f9fafb',
      },
      spacing: {
        paddingTop: '80px',
        paddingBottom: '80px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'contact',
    label: 'Contact Section',
    description: 'Contact information and form',
    icon: 'mail',
    variants: [
      { id: 'default', label: 'Split Layout' },
      { id: 'centered', label: 'Centered' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'Get in Touch',
      subtitle: 'We would love to hear from you',
      email: 'contact@example.com',
      phone: '+1 (555) 123-4567',
      address: '123 Business St, City, State 12345',
      showForm: true,
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#ffffff',
      },
      spacing: {
        paddingTop: '80px',
        paddingBottom: '80px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'footer',
    label: 'Footer',
    description: 'Site footer with links and info',
    icon: 'layout',
    category: 'navigation',
    unique: true,
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
      { id: 'centered', label: 'Centered' },
    ],
    defaultContent: {
      logo: '',
      logoText: 'Brand',
      description: 'Building amazing products for amazing people.',
      columns: [
        {
          title: 'Product',
          links: [
            { label: 'Features', url: '#' },
            { label: 'Pricing', url: '#' },
            { label: 'FAQ', url: '#' },
          ],
        },
        {
          title: 'Company',
          links: [
            { label: 'About', url: '#' },
            { label: 'Blog', url: '#' },
            { label: 'Careers', url: '#' },
          ],
        },
        {
          title: 'Legal',
          links: [
            { label: 'Privacy', url: '#' },
            { label: 'Terms', url: '#' },
          ],
        },
      ],
      socialLinks: [
        { platform: 'facebook', url: '#' },
        { platform: 'twitter', url: '#' },
        { platform: 'linkedin', url: '#' },
      ],
      copyright: '',
    },
    defaultDesign: {
      background: {
        type: 'color',
        value: '#111827',
      },
      spacing: {
        paddingTop: '0px',
        paddingBottom: '0px',
        marginTop: '0px',
        marginBottom: '0px',
      },
    },
  },
  {
    type: 'pricing',
    label: 'Pricing',
    description: 'Display pricing plans and packages',
    icon: 'dollar-sign',
    category: 'marketing',
    variants: [
      { id: 'cards', label: 'Cards' },
      { id: 'comparison', label: 'Comparison Table' },
      { id: 'toggle', label: 'Toggle Plans' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'Simple, Transparent Pricing',
      subtitle: 'Choose the perfect plan for your needs',
      plans: [
        {
          name: 'Starter',
          price: '$29',
          period: '/month',
          features: ['10 Projects', '5GB Storage', 'Basic Support'],
          popular: false,
        },
        {
          name: 'Professional',
          price: '$79',
          period: '/month',
          features: ['Unlimited Projects', '50GB Storage', 'Priority Support', 'Advanced Analytics'],
          popular: true,
        },
        {
          name: 'Enterprise',
          price: '$199',
          period: '/month',
          features: ['Unlimited Everything', 'Custom Storage', '24/7 Support', 'Dedicated Manager'],
          popular: false,
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'stats',
    label: 'Stats/Metrics',
    description: 'Display key statistics and metrics',
    icon: 'trending-up',
    category: 'content',
    variants: [
      { id: 'grid', label: 'Grid' },
      { id: 'gradient', label: 'Gradient Cards' },
      { id: 'minimalist', label: 'Minimalist' },
      { id: 'split', label: 'Split Layout' },
    ],
    defaultContent: {
      title: 'Trusted by Thousands',
      subtitle: 'Our numbers speak for themselves',
      stats: [
        { number: '10K+', label: 'Active Users', suffix: '+' },
        { number: '99%', label: 'Satisfaction Rate', suffix: '%' },
        { number: '50M', label: 'Downloads', suffix: 'M' },
        { number: '24/7', label: 'Support Available', suffix: '' },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'team',
    label: 'Team',
    description: 'Showcase your team members',
    icon: 'users',
    category: 'content',
    variants: [
      { id: 'grid', label: 'Grid' },
      { id: 'carousel', label: 'Carousel' },
      { id: 'bento', label: 'Bento Layout' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'Meet Our Team',
      subtitle: 'Talented individuals working together to create something amazing',
      members: [
        {
          name: 'Sarah Johnson',
          role: 'CEO & Founder',
          bio: 'Passionate about building innovative solutions',
          avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400',
          social: { linkedin: '#', twitter: '#', email: 'sarah@example.com' },
        },
        {
          name: 'Michael Chen',
          role: 'CTO',
          bio: 'Tech enthusiast with 15 years of experience',
          avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400',
          social: { linkedin: '#', twitter: '#', email: 'michael@example.com' },
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'faq',
    label: 'FAQ',
    description: 'Frequently asked questions section',
    icon: 'help-circle',
    category: 'content',
    variants: [
      { id: 'accordion', label: 'Accordion' },
      { id: 'two-columns', label: 'Two Columns' },
      { id: 'cards', label: 'Cards' },
      { id: 'gradient', label: 'Gradient' },
    ],
    defaultContent: {
      title: 'Frequently Asked Questions',
      subtitle: 'Find answers to common questions',
      faqs: [
        {
          question: 'How do I get started?',
          answer: 'Getting started is easy! Simply sign up for an account, choose your plan, and you\'ll have access to all our features immediately.',
        },
        {
          question: 'What payment methods do you accept?',
          answer: 'We accept all major credit cards, PayPal, and bank transfers for enterprise customers.',
        },
        {
          question: 'Can I cancel my subscription anytime?',
          answer: 'Yes, you can cancel your subscription at any time. Your access will continue until the end of your billing period.',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'logocloud',
    label: 'Logo Cloud',
    description: 'Display client and partner logos',
    icon: 'award',
    category: 'marketing',
    variants: [
      { id: 'grid', label: 'Grid' },
      { id: 'marquee', label: 'Marquee' },
      { id: 'featured', label: 'Featured' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'Trusted by Leading Companies',
      subtitle: 'Join thousands of satisfied customers',
      logos: [
        { name: 'Company 1', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+1' },
        { name: 'Company 2', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+2' },
        { name: 'Company 3', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+3' },
        { name: 'Company 4', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+4' },
        { name: 'Company 5', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+5' },
        { name: 'Company 6', url: 'https://via.placeholder.com/200x80/cccccc/666666?text=Logo+6' },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '64px', paddingBottom: '64px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'videohero',
    label: 'Video Hero',
    description: 'Hero section with video content',
    icon: 'video',
    category: 'content',
    variants: [
      { id: 'background', label: 'Background' },
      { id: 'embedded', label: 'Embedded' },
      { id: 'split', label: 'Split' },
      { id: 'modal', label: 'Modal' },
    ],
    defaultContent: {
      title: 'Watch Our Story',
      subtitle: 'Discover what makes us different',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      thumbnail: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1920',
      ctaText: 'Learn More',
      ctaLink: '#',
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '96px', paddingBottom: '96px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff', textColor: '#e5e7eb' },
    },
  },
  {
    type: 'gallery',
    label: 'Gallery',
    description: 'Image gallery or portfolio',
    icon: 'image',
    category: 'content',
    variants: [
      { id: 'masonry', label: 'Masonry' },
      { id: 'grid', label: 'Grid' },
      { id: 'featured', label: 'Featured' },
      { id: 'carousel', label: 'Carousel' },
    ],
    defaultContent: {
      title: 'Our Work',
      subtitle: 'A showcase of our latest projects',
      items: [
        {
          image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
          title: 'Project Alpha',
          category: 'Web Design',
          link: '#',
        },
        {
          image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=800',
          title: 'Project Beta',
          category: 'Branding',
          link: '#',
        },
        {
          image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
          title: 'Project Gamma',
          category: 'Mobile App',
          link: '#',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'timeline',
    label: 'Timeline',
    description: 'Display events in chronological order',
    icon: 'clock',
    category: 'content',
    variants: [
      { id: 'vertical', label: 'Vertical' },
      { id: 'horizontal', label: 'Horizontal' },
      { id: 'cards', label: 'Cards' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      title: 'Our Journey',
      subtitle: 'Milestones that shaped our story',
      events: [
        {
          date: '2020',
          title: 'Company Founded',
          description: 'Started with a vision to transform the industry',
          image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400',
        },
        {
          date: '2021',
          title: 'First Product Launch',
          description: 'Released our flagship product to amazing reception',
          image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=400',
        },
        {
          date: '2022',
          title: 'Series A Funding',
          description: 'Raised $10M to scale our operations',
          image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=400',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'newsletter',
    label: 'Newsletter',
    description: 'Email subscription form',
    icon: 'mail',
    category: 'marketing',
    variants: [
      { id: 'centered', label: 'Centered' },
      { id: 'split', label: 'Split' },
      { id: 'inline', label: 'Inline' },
      { id: 'card', label: 'Card' },
    ],
    defaultContent: {
      title: 'Stay Updated',
      subtitle: 'Subscribe to our newsletter for the latest updates and exclusive content',
      placeholder: 'Enter your email',
      buttonText: 'Subscribe',
      privacyNote: 'We respect your privacy. Unsubscribe at any time.',
      image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'process',
    label: 'Process/Steps',
    description: 'Show a step-by-step process',
    icon: 'list-ordered',
    category: 'content',
    variants: [
      { id: 'numbered', label: 'Numbered' },
      { id: 'cards', label: 'Cards' },
      { id: 'vertical', label: 'Vertical' },
      { id: 'grid', label: 'Grid' },
    ],
    defaultContent: {
      title: 'How It Works',
      subtitle: 'Get started in four simple steps',
      steps: [
        { number: '01', title: 'Sign Up', description: 'Create your account in less than a minute' },
        { number: '02', title: 'Set Up', description: 'Configure your preferences and settings' },
        { number: '03', title: 'Start Building', description: 'Begin creating your first project' },
        { number: '04', title: 'Launch', description: 'Go live and share with the world' },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'image-text-split',
    label: 'Image Text Split',
    description: 'Rich content section with image and styled text',
    icon: 'columns',
    variants: [
      { id: 'default', label: 'Image Left' },
      { id: 'image-right', label: 'Image Right' },
      { id: 'stacked', label: 'Stacked' },
    ],
    defaultContent: {
      subtitle: '',
      headline: 'Nemo enim quia sit asper natur sed magni dolores eos ratione serui nesciunt est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi.',
      paragraph1: 'Welcome to our digital sanctuary, an immersive space where the symphony of innovation and creativity harmoniously reverberates. As you step into this virtual realm, be prepared for a transformative journey that transcends the ordinary and delves deep into the extraordinary.',
      paragraph2: 'As you step into this virtual realm, be prepared for a transformative journey that transcends the ordinary and delves deep into the extraordinary. Here at our digital abode, we don\'t just design websites we orchestrate experiences, sculpting each pixel with intentionality and crafting narratives that leave an indelible mark.',
      paragraph3: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et magna aliqua minim veniam nostrud exercitation ullamco laboris nisi ut commodo consequat aute irure dolor in repreh enderit velit esse cillum dolor eu fugiat null.',
      ctaText: 'LEARN MORE',
      ctaLink: '#',
      image: 'https://images.pexels.com/photos/3184306/pexels-photo-3184306.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    },
    defaultDesign: {
      background: { type: 'color', value: '#F3F4F6' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'content-showcase',
    label: 'Content Showcase',
    description: 'Showcase content with subtitle, headline and columns',
    icon: 'layout',
    variants: [
      { id: 'default', label: 'Image Left' },
      { id: 'image-right', label: 'Image Right' },
      { id: 'two-column', label: 'Two Column Text' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      headline: 'Quis autem veleum iure repreh enderit.',
      column1: 'Sed unde omnis iste natus sit tatem accus antium laudan tium totam aperiam eaque ipsa ab illo inventore veritatis et architecto beatae vitae dicta explicabo.',
      column2: 'Nemo enim quia sit asper natur sed magni dolores eos ratione serui nesciunt dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi.',
      column3: 'Tempora incidunt ut labore magnam enim mini veniam nostrum exercita tionem ullam corporis suscipit ut aliquid commo.',
      image: 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'centered-content',
    label: 'Centered Content',
    description: 'Centered content with image and call-to-action',
    icon: 'align-center',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'compact', label: 'Compact' },
      { id: 'wide', label: 'Wide' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      headline: 'Development of Multimedia Interactive Content',
      description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et magna aliqua minim veniam nostrud exercitation ullamco laboris velit esse cillum nulla pariatur.',
      ctaText: 'Learn More',
      ctaLink: '#',
      image: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750',
    },
    defaultDesign: {
      background: { type: 'color', value: '#F3F4F6' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'text-columns',
    label: 'Text Columns',
    description: 'Introduction text with CTA and content columns',
    icon: 'columns',
    variants: [
      { id: 'default', label: 'Three Columns' },
      { id: 'two-column', label: 'Two Columns' },
      { id: 'centered', label: 'Centered' },
    ],
    defaultContent: {
      introduction: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa illo inventore veritatis et beatae vitae dicta sunt enim quia asper natur sed magni serui amet consec tetur adipisci.',
      ctaText: 'Learn More',
      ctaLink: '#',
      column1: 'Porro dolorem ipsum dolor amet consec tetur adipisci velit sed non modi incidunt magnam alisuam enim mini veniam nostrum exercita tionem ullam suscipit nisi ut aliquid commo autem repreh enderit in velit esse nihil molestiae vel illum dolorem fugiat.',
      column2: 'Porro dolorem ipsum dolor amet consec tetur adipisci velit sed non modi incidunt magnam alisuam enim mini veniam nostrum exercita tionem ullam suscipit nisi ut aliquid commo autem repreh enderit in velit esse nihil molestiae vel illum dolorem fugiat.',
      column3: 'Porro dolorem ipsum dolor amet consec tetur adipisci velit sed non modi incidunt magnam alisuam enim mini veniam nostrum exercita tionem ullam suscipit nisi ut aliquid commo autem repreh enderit in velit esse nihil molestiae vel illum dolorem fugiat.',
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'services-grid',
    label: 'Services Grid',
    description: 'Display services in a grid layout with links',
    icon: 'layout',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Check out the special features we offer.',
      description: 'Sed omnis lorem iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis et architecto beatae vitae dicta sunt explicabo.',
      services: [
        {
          icon: 'monitor',
          title: 'Responsive Layout Development',
          description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis architect.',
          link: '#',
          linkText: 'Learn More',
        },
        {
          icon: 'shield',
          title: 'Feedback & Support Implementation',
          description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis architect.',
          link: '#',
          linkText: 'Learn More',
        },
        {
          icon: 'lock',
          title: 'Website Security Enhancements',
          description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis architect.',
          link: '#',
          linkText: 'Learn More',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'contact-split',
    label: 'Contact Split',
    description: 'Contact section with info and form side by side',
    icon: 'phone',
    category: 'content',
    variants: [
      { id: 'default', label: 'Light' },
      { id: 'dark', label: 'Dark' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: "Let's talk design and innovation.",
      description: 'Sed ut unde omnis istera natus sit volur tatem accus antium laudan tium totam rem aperiam inventore verita.',
      phone: '0800 (212) 123 45 67',
      address: 'Dunlap Ave, Phoenix Arizona - USA',
      email: 'demo@yourwebsite.com',
      formTitle: 'Ask Us Anything',
      formDescription: 'Natus sit volur tatem accus antium laudan tium totam rem inventore veritatis et architecto beatae dicta sunt explicabo.',
      buttonText: 'Send Message',
    },
    defaultDesign: {
      background: { type: 'color', value: '#f3f4f6' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'feedback-contact',
    label: 'Feedback Contact',
    description: 'Dark background contact section with form',
    icon: 'message-circle',
    category: 'content',
    variants: [
      { id: 'default', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'User feedbacks shapes better designs.',
      description: 'Sed ut unde omnis istera natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis et architecto beatae vitae dicta sunt explicabo.',
      ctaText: 'Learn More',
      formTitle: 'Reach Us Here',
      formDescription: 'Natus sit volur tatem accus antium laudan tium totam rem inventore veritatis et architecto beatae dicta sunt explicabo.',
      buttonText: 'Send Message',
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff', textColor: '#9CA3AF' },
    },
  },
  {
    type: 'services-cards',
    label: 'Services Cards',
    description: 'Service cards with images and icons',
    icon: 'box',
    category: 'content',
    variants: [
      { id: 'dark', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Registration and Management Assistance',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam aperiam veritatis dicta sunt explicabo.',
      ctaText: 'Learn More',
      services: [
        {
          icon: 'umbrella',
          title: 'Video Production',
          description: 'Quis autem repreh enderit in velit esse nihil molestiae vel illum dolorem.',
          image: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
          link: '#',
          linkText: 'LEARN MORE',
        },
        {
          icon: 'layers',
          title: 'Reality Features',
          description: 'Quis autem repreh enderit in velit esse nihil molestiae vel illum dolorem.',
          image: 'https://images.pexels.com/photos/3184338/pexels-photo-3184338.jpeg?auto=compress&cs=tinysrgb&w=800',
          link: '#',
          linkText: 'LEARN MORE',
        },
        {
          icon: 'creditcard',
          title: 'Secure Payment',
          description: 'Quis autem repreh enderit in velit esse nihil molestiae vel illum dolorem.',
          image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
          link: '#',
          linkText: 'LEARN MORE',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff', textColor: '#9CA3AF' },
    },
  },
  {
    type: 'membership-pricing',
    label: 'Membership Pricing',
    description: 'Pricing cards with icons and feature lists',
    icon: 'credit-card',
    category: 'marketing',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'centered', label: 'Centered' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Membership Costs',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam aperiam veritatis vitae dicta sunt explicabo.',
      plans: [
        {
          icon: 'umbrella',
          name: 'Starter',
          subtitle: 'Suitable for Beginners',
          price: '$25',
          period: '/PER MONTH',
          features: [
            { text: 'Unlimited Bandwidth', included: true },
            { text: 'SEO Optimization', included: true },
            { text: 'Mobile App Integration', included: false },
            { text: 'Custom Domain', included: false },
            { text: 'Social Media Integration', included: false },
            { text: 'Uptime Guarantee', included: false },
          ],
          ctaText: 'Get Started',
          guarantee: 'Money Back Guaranteed',
          featured: false,
        },
        {
          icon: 'layers',
          name: 'Elegant',
          subtitle: 'Suitable for Beginners',
          price: '$47',
          period: '/PER MONTH',
          features: [
            { text: 'Unlimited Bandwidth', included: true },
            { text: 'SEO Optimization', included: true },
            { text: 'Mobile App Integration', included: true },
            { text: 'Custom Domain', included: true },
            { text: 'Social Media Integration', included: false },
            { text: 'Uptime Guarantee', included: false },
          ],
          ctaText: 'Get Started',
          guarantee: 'Money Back Guaranteed',
          featured: true,
        },
        {
          icon: 'paintbucket',
          name: 'Premium',
          subtitle: 'Suitable for Beginners',
          price: '$81',
          period: '/PER MONTH',
          features: [
            { text: 'Unlimited Bandwidth', included: true },
            { text: 'SEO Optimization', included: true },
            { text: 'Mobile App Integration', included: true },
            { text: 'Custom Domain', included: true },
            { text: 'Social Media Integration', included: true },
            { text: 'Uptime Guarantee', included: true },
          ],
          ctaText: 'Get Started',
          guarantee: 'Money Back Guaranteed',
          featured: false,
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f3f4f6' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'faq-two-columns',
    label: 'FAQ Two Columns',
    description: 'Frequently asked questions in two column layout',
    icon: 'help-circle',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Frequently Asked Questions',
      faqs: [
        {
          question: 'Lorem ipsum dolor sit amet consec?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
        {
          question: 'Culpa officia deserunt mollit est laborum?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
        {
          question: 'Exercitation ullamco laboris nisi ut commodo?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
        {
          question: 'Sed ut unde iste natus sit volur dolores tatem?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
        {
          question: 'Repreh enderit velit esse cillum dolor?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
        {
          question: 'Nemo enim sit asper natur sed magni?',
          answer: 'Porro est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam enim ad mini veniam nostrum exercita tionem ullam corporis.',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'integrations-grid',
    label: 'Integrations Grid',
    description: 'Display integrations and partnerships in a grid',
    icon: 'plug',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Integrations',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam aperiam veritatis dicta sunt explicabo.',
      integrations: [
        {
          name: 'Stripe',
          logo: '',
          description: 'Duis irure repreh velit esse cillum fugiat nulla.',
          link: '#',
          linkText: 'MORE',
        },
        {
          name: 'Zoom',
          logo: '',
          description: 'Duis irure repreh velit esse cillum fugiat nulla.',
          link: '#',
          linkText: 'MORE',
        },
        {
          name: 'Hubspot',
          logo: '',
          description: 'Duis irure repreh velit esse cillum fugiat nulla.',
          link: '#',
          linkText: 'MORE',
        },
        {
          name: 'Medium',
          logo: '',
          description: 'Duis irure repreh velit esse cillum fugiat nulla.',
          link: '#',
          linkText: 'MORE',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'hero-with-services',
    label: 'Hero with Services',
    description: 'Hero section with service icons below',
    icon: 'layout',
    category: 'content',
    variants: [
      { id: 'dark', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Website Performance and Speed Optimization Techniques',
      description: 'Nemo enim quia sit asper natur sed magni dolores eos ratione serui nesciunt est dolorem ipsum dolor sit amet consec tetur adipisci velit sed non numsuam modi tempora incidunt ut labore magnam alisuam suscipit nisi ut aliquid commo.',
      ctaText: 'Learn More',
      phone: '0800 987 65 43',
      services: [
        {
          icon: 'umbrella',
          title: 'Web Analytic Setup Customization',
        },
        {
          icon: 'layers',
          title: 'Advanced Security Measures',
        },
        {
          icon: 'paintbucket',
          title: 'Media Management Integration',
        },
        {
          icon: 'clock',
          title: 'Corporate Branding and Identity',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff', textColor: '#9CA3AF' },
    },
  },
  {
    type: 'image-stats-faq',
    label: 'Image Stats FAQ',
    description: 'Image with stats overlay and FAQ section',
    icon: 'image',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'compact', label: 'Compact' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Unique sites give users smooth journeys.',
      image: 'https://images.pexels.com/photos/3184306/pexels-photo-3184306.jpeg?auto=compress&cs=tinysrgb&w=800',
      badge: 'ABOUT US • ABOUT US • ABOUT US • ',
      stats: [
        {
          label: 'Experience',
          value: '8502+',
          subtitle: 'SAMPLE SUBTITLE',
        },
        {
          label: 'Experience',
          value: '6428+',
          subtitle: 'SAMPLE SUBTITLE',
        },
      ],
      faqs: [
        {
          prefix: '—',
          question: 'Lorem ipsum dolor sit amet consec tetur?',
          answer: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore.',
          expandable: false,
        },
        {
          prefix: '+',
          question: 'Enim ad minim veniam nostrud exercitation ullamco',
          expandable: true,
        },
        {
          prefix: '+',
          question: 'Rapsum amet consec tetur adipisci velit?',
          expandable: true,
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'timeline-grid',
    label: 'Timeline Grid',
    description: 'Timeline events displayed in a grid layout',
    icon: 'calendar',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'compact', label: 'Compact' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: "Find out about our company's background.",
      events: [
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
        {
          period: '1985 - 2013',
          title: 'This is heading',
          description: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et aliqua exceur sante.',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f3f4f6' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'newsletter-signup',
    label: 'Newsletter Signup',
    description: 'Newsletter subscription form with inline button',
    icon: 'mail',
    category: 'marketing',
    variants: [
      { id: 'dark', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Sign up now for exclusive contents.',
      description: 'Sed unde omnis iste natus sit volur tatem accus antium laudan tium totam aperiam veritatis exceur sante vitae dicta sunt explicabo.',
      placeholder: 'Your Email Address',
      buttonText: 'SUBSCRIBE',
      note: 'We respect your privacy. Unsubscribe at any time.',
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff', textColor: '#9CA3AF' },
    },
  },
  {
    type: 'social-follow',
    label: 'Social Follow',
    description: 'Social media links with call-to-action',
    icon: 'share-2',
    category: 'marketing',
    variants: [
      { id: 'dark', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      title: 'Follow Us',
      socials: [
        { platform: 'facebook', url: '#' },
        { platform: 'twitter', url: '#' },
        { platform: 'youtube', url: '#' },
        { platform: 'instagram', url: '#' },
        { platform: 'linkedin', url: '#' },
      ],
      ctaText: 'Learn More',
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '40px', paddingBottom: '40px', marginTop: '0px', marginBottom: '0px' },
      typography: { headingColor: '#ffffff' },
    },
  },
  {
    type: 'services-carousel',
    label: 'Services Carousel',
    description: 'Services displayed in carousel cards with icons',
    icon: 'layers',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      showDots: true,
      services: [
        {
          icon: 'umbrella',
          title: 'Site Performance and Speed',
          description: '',
          link: '#',
        },
        {
          icon: 'layers',
          title: 'Ongoing Website Maintenance',
          description: '',
          link: '#',
        },
        {
          icon: 'paintbucket',
          title: 'Domain Name Registration',
          description: '',
          link: '#',
        },
        {
          icon: 'clock',
          title: 'Customized Data Designer',
          description: '',
          link: '#',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'bento-features',
    label: 'Bento Features',
    description: 'Feature cards in bento/masonry layout',
    icon: 'grid',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'compact', label: 'Compact' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Discover the benefits of unique features.',
      features: [
        {
          label: 'FEATURE',
          title: 'Digital Presence',
          size: 'small',
          height: 'tall',
        },
        {
          label: 'FEATURE',
          title: 'Concept Design',
          size: 'medium',
          height: 'normal',
        },
        {
          label: 'FEATURE',
          title: 'Media Integration',
          size: 'medium',
          height: 'tall',
        },
        {
          label: 'FEATURE',
          title: 'Hosting Setup',
          size: 'medium',
          height: 'normal',
        },
        {
          label: 'FEATURE',
          title: 'Content Management',
          size: 'medium',
          height: 'normal',
        },
        {
          label: 'FEATURE',
          title: 'Security Solutions',
          size: 'small',
          height: 'tall',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      colors: { cardBackground: '#9CA3AF' },
    },
  },
  {
    type: 'features-carousel',
    label: 'Features Carousel',
    description: 'Carousel of feature cards with centered icons',
    icon: 'sparkles',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'bordered', label: 'With Borders' },
    ],
    defaultContent: {
      showDots: true,
      features: [
        {
          icon: 'umbrella',
          title: 'Chat Support',
          description: 'Duis aute irure dolor in repreh enderit velit esse cillum nulla pariatur sint proident culpa officia.',
          ctaText: 'Learn More',
          featured: false,
        },
        {
          icon: 'layers',
          title: 'Survey Forms',
          description: 'Duis aute irure dolor in repreh enderit velit esse cillum nulla pariatur sint proident culpa officia.',
          ctaText: 'Learn More',
          featured: true,
        },
        {
          icon: 'paintbucket',
          title: 'Custom Widget',
          description: 'Duis aute irure dolor in repreh enderit velit esse cillum nulla pariatur sint proident culpa officia.',
          ctaText: 'Learn More',
          featured: false,
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'content-with-services',
    label: 'Content with Services',
    description: 'Split layout with content and services grid',
    icon: 'layout',
    category: 'content',
    variants: [
      { id: 'two-services', label: 'Two Services' },
      { id: 'four-services', label: 'Four Services' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Website Performance and Speed Optimization Techniques',
      description: 'Sed unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam illo inventore veritatis et architecto beatae vitae dicta sunt explicabo.',
      additionalText: 'Lorem ipsum dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor labore magna aliqua.',
      ctaText: 'Learn More',
      image: true,
      imageLabel: 'new-container-image-2',
      showDots: true,
      services: [
        {
          icon: 'umbrella',
          title: 'Domain Name Registration and Management Assistance',
        },
        {
          icon: 'paintbucket',
          title: 'Development of Multimedia and Interactive Content',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      colors: { servicesBackground: '#f3f4f6' },
    },
  },
  {
    type: 'split-content-checklist',
    label: 'Split Content with Checklist',
    description: 'Split layout with content and checklist on left, image on right',
    icon: 'check-square',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'with-divider', label: 'With Divider' },
    ],
    defaultContent: {
      title: 'Quis autem veleum repreh enderit.',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam rem aperiam eaque ipsa ab illo inventore veritatis et architecto beatae vitae dicta sunt explicabo.',
      divider: true,
      checklist: ['Web Design', 'Landing Page', 'Survey Forms'],
      image: '',
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'dropcap-services',
    label: 'Drop Cap with Services',
    description: 'Content with drop cap letter and service columns',
    icon: 'type',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'with-signature', label: 'With Signature' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Quis autem veleum iure repreh enderit.',
      dropCap: 'W',
      introText: 'edut omnis volur tatem accus antim laudan totam aperiam eaque ipsa ab illo inventore veritatis et exceurs architecto beatae vitae dicta sunt explicabo.',
      additionalText: 'Dolores eos ratione serui nesciunt porro est dolorem ipsum exceur sante monaco millet dolor sit amet consec tetur stare class litsum rears adipisci sed numsuam modi tempora.',
      signature: '',
      serviceColumns: [
        {
          title: 'Why Choose Us',
          items: [
            'Experience Seo Consulting',
            'Mobile-First Website Designs',
            'Advertise Management',
            'Mobile Page Optimization',
            'Corporate Branding',
          ],
          ctaText: 'Learn More',
          ctaLink: '#',
        },
        {
          title: 'New Services',
          items: [
            'Experience Seo Consulting',
            'Mobile-First Website Designs',
            'Advertise Management',
            'Mobile Page Optimization',
            'Corporate Branding',
          ],
          ctaText: 'Learn More',
          ctaLink: '#',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'centered-testimonial',
    label: 'Centered Testimonial',
    description: 'Centered content with two text columns and signature',
    icon: 'quote',
    category: 'testimonials',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'with-signature', label: 'With Signature' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Why Choose Us',
      textBlocks: [
        'Lorem dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et magna aliqua ad minim veniam nostrud exercitation ullamco laboris aute irure enderit.',
        'Lorem dolor sit amet consec tetur adipis cing elit sed do eiusmod tempor ut labore et magna aliqua ad minim veniam nostrud exercitation ullamco laboris aute irure enderit.',
      ],
      signature: '',
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'content-video-services',
    label: 'Content Video Services',
    description: '3-column layout with content, video, and services',
    icon: 'play-circle',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'dark', label: 'Dark' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Digital Marketing and Strategy.',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam eaque ipsa ab illo inventore et architecto beatae vitae dicta sunt explicabo.',
      additionalText: 'Ecitation ullamco laboris nisi ut commodo in repreh enderit velit esse cillum',
      ctaText: 'Learn More',
      videoUrl: '',
      services: [
        {
          icon: 'umbrella',
          title: 'Ensuring Website Compliance',
        },
        {
          icon: 'layers',
          title: 'Creation Virtual Reality Blog',
        },
        {
          icon: 'paintbucket',
          title: 'Business Email Solutions',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'process-alternating',
    label: 'Process Alternating Grid',
    description: 'Alternating grid of process steps with images and numbered items',
    icon: 'workflow',
    category: 'content',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'with-cta', label: 'With Header CTA' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'See how processes go success.',
      headerDescription: 'Amnis natus volur tatem accus antium laudan exceurs totam rem aperiam eaque ipsa ab illo inventore veritatis et architecto vitae dicta sunt explicabo.',
      headerCta: 'Learn More',
      steps: [
        {
          image: '',
          title: 'Chat Support',
          description: 'Quis autem repreh in velit esse nihil fugiat voluptas.',
          ctaText: 'Learn More',
          ctaLink: '#',
        },
        {
          image: '',
          title: 'Survey Forms',
          description: 'Quis autem repreh in velit esse nihil fugiat voluptas.',
          ctaText: 'Learn More',
          ctaLink: '#',
        },
        {
          image: '',
          title: 'Landing Page',
          description: 'Quis autem repreh in velit esse nihil fugiat voluptas.',
          ctaText: 'Learn More',
          ctaLink: '#',
        },
        {
          image: '',
          title: 'Secure Pays',
          description: 'Quis autem repreh in velit esse nihil fugiat voluptas.',
          ctaText: 'Learn More',
          ctaLink: '#',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'hero-with-testimonials',
    label: 'Hero with Testimonials',
    description: 'Dark hero section with overlapping testimonial cards',
    icon: 'message-square',
    category: 'hero',
    variants: [
      { id: 'dark', label: 'Dark' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      subtitle: 'SAMPLE SUBTITLE',
      title: 'Corporate Branding Design Services',
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium laudan tium totam aperiam dicta sunt explicabo.',
      ctaText: 'Learn More',
      testimonials: [
        {
          avatar: '',
          name: 'User 1',
          text: 'Sed ut unde omnis iste natus volur tatem accus antium tium.',
        },
        {
          avatar: '',
          name: 'User 2',
          text: 'Sed ut unde omnis iste natus volur tatem accus antium tium.',
        },
        {
          avatar: '',
          name: 'User 3',
          text: 'Sed ut unde omnis iste natus volur tatem accus antium tium.',
        },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#000000' },
      spacing: { paddingTop: '120px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      colors: { cardBackground: '#ffffff' },
    },
  },
  {
    type: 'brand-identity-hero',
    label: 'Brand Identity Hero',
    description: 'Typography-focused hero with decorative circle and social icons',
    icon: 'type',
    category: 'hero',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      badge1: 'User Interface Design for Enhanced Usability',
      badge2: '',
      circleText: 'Fast Support',
      title1: 'CORPORATE BRAND',
      title2: 'IDENTITY SERVICES',
      accent: '*',
      ctaLinks: [
        { text: 'Support Area', url: '#' },
        { text: 'Learn More', url: '#' },
      ],
      socialLinks: [
        { icon: 'facebook', url: '#' },
        { icon: 'twitter', url: '#' },
        { icon: 'youtube', url: '#' },
      ],
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '80px', paddingBottom: '80px', marginTop: '0px', marginBottom: '0px' },
      colors: { circleBg: '#000000', circleText: '#ffffff' },
    },
  },
  {
    type: 'simple-centered-hero',
    label: 'Simple Centered Hero',
    description: 'Minimal centered hero with badge subtitle',
    icon: 'align-center',
    category: 'hero',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'large', label: 'Large' },
    ],
    defaultContent: {
      subtitle: 'Sample Subtitle',
      title: 'Quis autem veleum iure repreh enderit.',
    },
    defaultDesign: {
      background: { type: 'color', value: '#f9fafb' },
      spacing: { paddingTop: '120px', paddingBottom: '120px', marginTop: '0px', marginBottom: '0px' },
      colors: { badgeBg: '#000000', badgeText: '#ffffff' },
    },
  },
  {
    type: 'simple-header-divider',
    label: 'Simple Header Divider',
    description: 'Minimal centered header with title and decorative line',
    icon: 'minus',
    category: 'header',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'thin', label: 'Thin Line' },
    ],
    defaultContent: {
      title: 'Sample Header Text',
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '60px', paddingBottom: '60px', marginTop: '0px', marginBottom: '0px' },
      colors: { dividerColor: '#111827' },
    },
  },
  {
    type: 'header-top-info',
    label: 'Header Top Info',
    description: 'Two-row header with top info bar and navigation',
    icon: 'layout',
    category: 'header',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'compact', label: 'Compact' },
    ],
    defaultContent: {
      openHoursTitle: 'Open Hours',
      openHours: 'Mon - Fri 9:30 - 20:00',
      logo: 'KING',
      phone: '1-800 444 22 55',
      ctaText: 'Learn More',
      showSearch: true,
      showCart: true,
      menuItems: ['HOME', 'ABOUT', 'SERVICES', 'PORTFOLIO', 'OUR TEAM', 'CONTACT'],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '0px', paddingBottom: '0px', marginTop: '0px', marginBottom: '0px' },
    },
  },
  {
    type: 'header-with-icons',
    label: 'Header with Icons',
    description: 'Multi-row header with account bar, info section and navigation',
    icon: 'layers',
    category: 'header',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'light', label: 'Light' },
    ],
    defaultContent: {
      showAccount: true,
      showSupport: true,
      email: 'demo@section.express',
      socialLinks: [
        { icon: 'facebook', url: '#' },
        { icon: 'twitter', url: '#' },
        { icon: 'youtube', url: '#' },
      ],
      openHoursTitle: 'Open Hours',
      openHours: 'Mon - Fri 9:30 - 20:00',
      logo: 'KING',
      phone: '1-800-444-22 555',
      menuItems: ['HOME', 'ABOUT', 'SERVICES', 'PORTFOLIO', 'OUR TEAM', 'CONTACT'],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '0px', paddingBottom: '0px', marginTop: '0px', marginBottom: '0px' },
      colors: { topBarBg: '#f3f4f6' },
    },
  },
  {
    type: 'header-account-bar',
    label: 'Header Account Bar',
    description: 'Header with top bar, social icons and call to action',
    icon: 'layout-grid',
    category: 'header',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'minimal', label: 'Minimal' },
    ],
    defaultContent: {
      socialLinks: [
        { icon: 'facebook', url: '#' },
        { icon: 'twitter', url: '#' },
        { icon: 'youtube', url: '#' },
      ],
      description: 'Sed ut unde omnis iste natus sit volur tatem accus antium.',
      logo: 'KING',
      phone: '1-800-444-22 555',
      menuItems: ['HOME', 'ABOUT', 'SERVICES', 'PORTFOLIO', 'OUR TEAM', 'CONTACT'],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '0px', paddingBottom: '0px', marginTop: '0px', marginBottom: '0px' },
      colors: { topBarBg: '#f3f4f6' },
    },
  },
  {
    type: 'header-full-contact',
    label: 'Header Full Contact',
    description: 'Complete header with all contact information and CTA button',
    icon: 'phone',
    category: 'header',
    variants: [
      { id: 'default', label: 'Standard' },
      { id: 'dark', label: 'Dark' },
    ],
    defaultContent: {
      openHours: 'Mon - Fri 9:30 - 20:00',
      email: 'demo@section.express',
      address: '68 Apple Street Newyork',
      socialLinks: [
        { icon: 'facebook', url: '#' },
        { icon: 'twitter', url: '#' },
        { icon: 'youtube', url: '#' },
      ],
      logo: 'KING',
      phone: '1-800 444 22 55',
      ctaText: 'Learn More',
      menuItems: ['HOME', 'ABOUT', 'FEATURES', 'SHOP', 'CONTACT'],
    },
    defaultDesign: {
      background: { type: 'color', value: '#ffffff' },
      spacing: { paddingTop: '0px', paddingBottom: '0px', marginTop: '0px', marginBottom: '0px' },
      colors: { topBarBg: '#f3f4f6', buttonBg: '#000000', buttonText: '#ffffff' },
    },
  },
];
